### PR TITLE
fix default install dir for phobos

### PR DESCRIPTION
**Pull request by biobootstrap**

### CODE REVIEW

**Comment by adamdruppe** [comment]
...are you sure? i guess this is to put it outside the tree, right?

**Comment by adamdruppe** [comment]
yeah this matches what it used to do at least. huh might change it again alter

**Comment by biobootstrap** [comment]
yeah, phobos was moved inside dmd, which caused it to install into dmd's tree

**Comment by adamdruppe** [comment]
yeah

**Pull request merged**
