### PR TITLE
Renames ldc2 binary to lodc

### PR DESCRIPTION
**Pull request by denizzzka**
...but does not touches cmake config file names

### CODE REVIEW

**Comment by IgorDeepakM** [comment]
Shouldn't it be lodc2 instead of oldc2?

ldc2 = LLVM D compiler 2
oldc2 = open LLVM D compiler 2
lodc2 = LLVM openD compiler 2

Do we need the 2 in the end ?

**Comment by adamdruppe** [comment]
will have to update the github action too to call the right one and copy the right one..... maybe we should only edit the name in the binary release package instead of the whole thing....

the 2 is probably not really needed here btw, that was to differentiate between D1 and D2 and D1 is quite dead now.

**Comment by denizzzka** [comment]
@IgorDeepakM don't know, can change to any other

I am only worrying about mess with original ldc2 because Meson obviously isn't supports opend

**Comment by IgorDeepakM** [comment]
> @IgorDeepakM don't know, can change to any other
> 
> I am only worrying about mess with original ldc2 because Meson obviously isn't supports opend

Yes, that is risk and also any plugins like code-D for VSCode.

Anyway, I'm good with any of the alternatives but just get rid of the 2 because we aren't making sequel .... wait are we?

It's no hurry for me but I think we should have a distinctive compiler names for the release so that they don't interfere with the old D compiler.

**Comment by denizzzka** [comment]
Ok, `lodc`, because oldc sounds like "old c"

**Comment by adamdruppe** [comment]
the filenames in the folder are the same but they can be driven through the opend ldc program now

**Pull request closed without merging**
