### PR TITLE
Unittest thing

### PR DESCRIPTION
**Pull request by adamdruppe**
@maxhaton we could merge here

### CODE REVIEW

**Comment by maxhaton** [comment]
So I said the UDAs might have to go because of bootstrapping but I'm now thinking maybe the exact mix of "bootstrap compiler builds x builds y" might be wrong?

Anyway my plan for this is to get my changes into the test runner because otherwise this will just make the druntime tests red forever. You can do whatever you want but I would recommend holding off just for a little bit.

**Comment by adamdruppe** [comment]
ok, i'll leave it here for a bit, when ready I can pull from your upstream branch again and get it in here as well.

**Comment by maxhaton** [comment]
Not sure if you need the extra commit btw.

Normally it doesn't matter *thaaaat* much, but ideally OpenD becomes a gleaming star of the wider D ecosystem and the parent converges with child so being able to cleanly revert and merge will help you

**Comment by maxhaton** [comment]
Nic merged my test runner PR, you should grab that one

**Comment by maxhaton** [comment]
https://github.com/dlang/dmd/pull/16006#event-11436118755

**Comment by adamdruppe** [comment]
idk git that well it just made that thing automatically i think because the things have diverged. maybe i could try again w/ --rebase but there is a merge conflict i had to settle with the ldc merge.

**Pull request merged**
